// ══════════════════════════════════════════════════════════════
// positions.js  ―  保有銘柄データ & 期間設定
//
// ★ positions 配列は合成値のフォールバック（実保有は KV / data/mf-holdings.json）。PERIODS の編集はここ
//
// positions 配列の各フィールド:
//   symbol  : 表示用ティッカー（例: "AAPL", "9983", "オルカン"）
//   name    : 銘柄名
//   cat     : カテゴリ（"日本株・ETF" | "米国株・ETF" | "投資信託"）
//   shares  : 保有数量（株・口）
//   price   : 現在値（CSVロード時点の値、ライブ更新で上書きされる）
//   avgCost : 平均取得単価
//   value   : 時価評価額（円建て）
//   pnl     : 含み損益（円建て）
//   pnlPct  : 損益率（%）
//   dayPct  : 当日騰落率（%）。null = APIから取得
//   dayCh   : 当日評価損益変化（円建て）。null = APIから取得
//   cur     : 通貨（"JPY" | "USD"）
//   ySymbol : Yahoo Finance ティッカー（チャート・価格取得に使用）
//   isProxy : true の場合、ySymbol は代替銘柄（投資信託など）
//   proxyName: 代替銘柄の説明名
// ══════════════════════════════════════════════════════════════

// ══════════════════════════════════════════════
// POSITION DATA（合成値のフォールバック）
//   ここの数量・単価・評価額・損益はすべて合成値（実際の保有とは無関係）。
//   実際の保有は KV（GET /positions）/ data/mf-holdings.json から読み込まれる。
//   USD 建ての value/pnl は 1USD=150円 換算、投資信託の price は 1万口あたり。
// ══════════════════════════════════════════════
const positions = [
  // 日本株・ETF
  {
    symbol: '1306',
    name: 'NEXT FUNDS TOPIX連動型上場投信',
    cat: '日本株・ETF',
    shares: 1000,
    price: 400,
    avgCost: 350,
    value: 400000,
    pnl: 50000,
    pnlPct: 14.29,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '1306.T',
  },
  {
    symbol: '1615',
    name: 'NEXT FUNDS 東証銀行業ETF',
    cat: '日本株・ETF',
    shares: 1000,
    price: 600,
    avgCost: 500,
    value: 600000,
    pnl: 100000,
    pnlPct: 20.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '1615.T',
  },
  {
    symbol: '1629',
    name: 'NEXT FUNDS 商社・卸売ETF',
    cat: '日本株・ETF',
    shares: 1000,
    price: 300,
    avgCost: 250,
    value: 300000,
    pnl: 50000,
    pnlPct: 20.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '1629.T',
  },
  {
    symbol: '200A',
    name: 'NEXT FUNDS 日経半導体ETF',
    cat: '日本株・ETF',
    shares: 100,
    price: 4000,
    avgCost: 3000,
    value: 400000,
    pnl: 100000,
    pnlPct: 33.33,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '200A.T',
  },
  {
    symbol: '6301',
    name: '小松製作所',
    cat: '日本株・ETF',
    shares: 100,
    price: 5000,
    avgCost: 4000,
    value: 500000,
    pnl: 100000,
    pnlPct: 25.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '6301.T',
  },
  {
    symbol: '8050',
    name: 'セイコーグループ',
    cat: '日本株・ETF',
    shares: 100,
    price: 6000,
    avgCost: 5000,
    value: 600000,
    pnl: 100000,
    pnlPct: 20.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '8050.T',
  },
  {
    symbol: '9983',
    name: 'ファーストリテイリング',
    cat: '日本株・ETF',
    shares: 100,
    price: 70000,
    avgCost: 60000,
    value: 7000000,
    pnl: 1000000,
    pnlPct: 16.67,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '9983.T',
  },
  // 米国株・ETF
  {
    symbol: 'AAPL',
    name: 'アップル',
    cat: '米国株・ETF',
    shares: 10,
    price: 300,
    avgCost: 200,
    value: 450000,
    pnl: 150000,
    pnlPct: 50.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'AAPL',
  },
  {
    symbol: 'AMZN',
    name: 'アマゾン',
    cat: '米国株・ETF',
    shares: 10,
    price: 250,
    avgCost: 200,
    value: 375000,
    pnl: 75000,
    pnlPct: 25.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'AMZN',
  },
  {
    symbol: 'COPX',
    name: 'グローバルX 銅ビジネスETF',
    cat: '米国株・ETF',
    shares: 10,
    price: 100,
    avgCost: 80,
    value: 150000,
    pnl: 30000,
    pnlPct: 25.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'COPX',
  },
  {
    symbol: 'GLDM',
    name: 'SPDR ゴールド・ミニシェアーズ',
    cat: '米国株・ETF',
    shares: 10,
    price: 100,
    avgCost: 90,
    value: 150000,
    pnl: 15000,
    pnlPct: 11.11,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'GLDM',
  },
  {
    symbol: 'GOOGL',
    name: 'アルファベット',
    cat: '米国株・ETF',
    shares: 10,
    price: 400,
    avgCost: 200,
    value: 600000,
    pnl: 300000,
    pnlPct: 100.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'GOOGL',
  },
  {
    symbol: 'ILF',
    name: 'iシェアーズ ラテンアメリカ40',
    cat: '米国株・ETF',
    shares: 10,
    price: 40,
    avgCost: 30,
    value: 60000,
    pnl: 15000,
    pnlPct: 33.33,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'ILF',
  },
  {
    symbol: 'JPST',
    name: 'JPモルガン ウルトラショート・インカムETF',
    cat: '米国株・ETF',
    shares: 10,
    price: 50,
    avgCost: 50,
    value: 75000,
    pnl: 0,
    pnlPct: 0.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'JPST',
  },
  {
    symbol: 'MSFT',
    name: 'マイクロソフト',
    cat: '米国株・ETF',
    shares: 10,
    price: 400,
    avgCost: 450,
    value: 600000,
    pnl: -75000,
    pnlPct: -11.11,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'MSFT',
  },
  {
    symbol: 'PLTR',
    name: 'パランティア・テクノロジーズ',
    cat: '米国株・ETF',
    shares: 10,
    price: 150,
    avgCost: 100,
    value: 225000,
    pnl: 75000,
    pnlPct: 50.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'PLTR',
  },
  {
    symbol: 'REMX',
    name: 'ヴァンエック レアアース・金属ETF',
    cat: '米国株・ETF',
    shares: 10,
    price: 100,
    avgCost: 80,
    value: 150000,
    pnl: 30000,
    pnlPct: 25.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'REMX',
  },
  {
    symbol: 'SHLD',
    name: 'グローバルX 防衛テックETF',
    cat: '米国株・ETF',
    shares: 10,
    price: 60,
    avgCost: 70,
    value: 90000,
    pnl: -15000,
    pnlPct: -14.29,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'SHLD',
  },
  {
    symbol: 'SLV',
    name: 'iシェアーズ シルバー・トラスト',
    cat: '米国株・ETF',
    shares: 10,
    price: 80,
    avgCost: 70,
    value: 120000,
    pnl: 15000,
    pnlPct: 14.29,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'SLV',
  },
  {
    symbol: 'SMH',
    name: 'ヴァンエック半導体ETF',
    cat: '米国株・ETF',
    shares: 10,
    price: 500,
    avgCost: 300,
    value: 750000,
    pnl: 300000,
    pnlPct: 66.67,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'SMH',
  },
  {
    symbol: 'TSLA',
    name: 'テスラ',
    cat: '米国株・ETF',
    shares: 10,
    price: 400,
    avgCost: 300,
    value: 600000,
    pnl: 150000,
    pnlPct: 33.33,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'TSLA',
  },
  {
    symbol: 'XLE',
    name: 'エネルギー・セレクト・セクター SPDR ETF',
    cat: '米国株・ETF',
    shares: 10,
    price: 60,
    avgCost: 65,
    value: 90000,
    pnl: -7500,
    pnlPct: -7.69,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'XLE',
  },
  // 投資信託
  {
    symbol: 'オルカン',
    name: 'eMAXIS Slim 全世界株式(AC)',
    cat: '投資信託',
    shares: 1000000,
    price: 30000,
    avgCost: 25000,
    value: 3000000,
    pnl: 500000,
    pnlPct: 20.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: 'ACWI',
    isProxy: true,
    proxyName: 'iShares MSCI ACWI ETF',
  },
  {
    symbol: 'ひふみ',
    name: 'ひふみ投信',
    cat: '投資信託',
    shares: 1000000,
    price: 90000,
    avgCost: 60000,
    value: 9000000,
    pnl: 3000000,
    pnlPct: 50.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '1306.T',
    isProxy: true,
    proxyName: 'TOPIX連動型ETF (1306)',
  },
  {
    symbol: 'マイクロSP',
    name: 'ひふみマイクロスコープpro',
    cat: '投資信託',
    shares: 1000000,
    price: 12000,
    avgCost: 10000,
    value: 1200000,
    pnl: 200000,
    pnlPct: 20.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '1477.T',
    isProxy: true,
    proxyName: 'iShares MSCIジャパン小型株ETF (1477)',
  },
  {
    symbol: 'ひふみXO',
    name: 'ひふみクロスオーバーpro',
    cat: '投資信託',
    shares: 1000000,
    price: 13000,
    avgCost: 10000,
    value: 1300000,
    pnl: 300000,
    pnlPct: 30.0,
    dayPct: null,
    dayCh: null,
    cur: 'JPY',
    ySymbol: '2516.T',
    isProxy: true,
    proxyName: '東証グロース市場250ETF (2516)',
  },
  {
    symbol: 'PIMCO-ST',
    name: 'ピムコ ショート・ターム ストラテジー USD',
    cat: '投資信託',
    shares: 10,
    price: 120,
    avgCost: 120,
    value: 180000,
    pnl: 0,
    pnlPct: 0.0,
    dayPct: null,
    dayCh: null,
    cur: 'USD',
    ySymbol: 'SHV',
    isProxy: true,
    proxyName: 'iShares Short Treasury Bond ETF',
  },
];

// ══════════════════════════════════════════════
// PERIODS CONFIG
// ══════════════════════════════════════════════
const PERIODS = [
  { id: '1d', label: '1d', statsLabel: '1d', days: 1, range: '1y', scale: 4 },
  { id: '1w', label: '1w', statsLabel: '1w', days: 7, range: '1y', scale: 8 },
  { id: '1m', label: '1m', statsLabel: '1m', days: 30, range: '1y', scale: 15 },
  { id: '3m', label: '3m', statsLabel: '3m', days: 91, range: '1y', scale: 25 },
  { id: '6m', label: '6m', statsLabel: '6m', days: 182, range: '5y', scale: 40 },
  { id: '9m', label: '9m', statsLabel: '9m', days: 273, range: '5y', scale: 55 },
  { id: '1y', label: '1y', statsLabel: '1y', days: 365, range: '5y', scale: 65 },
  { id: '3y', label: '3y', statsLabel: '3y', days: 1095, range: '5y', scale: 90 },
  { id: '5y', label: '5y', statsLabel: '5y', days: 1825, range: '5y', scale: 130 },
  { id: '10y', label: '10y', statsLabel: '10y', days: 3650, range: '10y', scale: 200 },
];
const PERIOD_MAP = Object.fromEntries(PERIODS.map((p) => [p.id, p]));
// テーブルヘッダー・セル描画用（PERIODS から自動生成）
const PERIOD_COLS = PERIODS.map((p) => ({ id: p.id, label: p.label }));
const PERIOD_IDS = PERIOD_COLS.map((pc) => pc.id);

export { positions, PERIODS, PERIOD_MAP, PERIOD_COLS, PERIOD_IDS };
